all:
	sudo cp .CEO.sh CEO.sh
	sudo cp .ceo_server ceo_server
	sudo chown root:root CEO.sh
	sudo chmod u+x CEO.sh
	sudo chown root:root ceo_server
	sudo chmod u+x ceo_server
	sudo cp CEO.sh /etc/init.d/
	sudo /etc/init.d/CEO.sh start
