source:
  photometric_band: R+I
  zenith: 0
  azimuth: 0
  magnitude: 0
  rays_box_size: 25.5000
  rays_box_sampling: 385 # N_SIDE_LENSLET*16+1 (16 pixel per lenslet)
  rays_origin: [0,0,25]
sensor:
  class: GeometricShackHartmann
  args:
    N_SIDE_LENSLET: 24 
    d: 1.0625 # [meter], rays_box_size/N_SIDE_LENSLET
  calibrate_args:
    threshold: 0.5
interaction matrices: 
  calibrations:
    M2TT:
      method_id: calibrate
      args:
        mirror: M2
        mode: segment tip-tilt
        stroke: 1.0e-06
  filename: M2TT24

